NoteBookStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NoteBookStore.Domain.Abstract;
using NoteBookStore.WebUI.Models;

namespace NoteBookStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private INoteBookRepository repository;
        public NavController(INoteBookRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string category = null)
        {
            NoteBooksCategoryViewModel model = new NoteBooksCategoryViewModel
            {
                //вывод всех категорий.
                Categories = repository.NoteBooks
                .Select(notebook => notebook.Category)
                .Distinct()
                .OrderBy(x => x),
                SelectedCategory = category
            };
            return PartialView(model);
        }
    }
}

NoteBookStore.WebUI/Controllers/NotebookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NoteBookStore.Domain.Abstract;
using NoteBookStore.Domain.Entities;
using NoteBookStore.WebUI.Models;

namespace NoteBookStore.WebUI.Controllers
{
    public class NoteBookController : Controller
    {
        private INoteBookRepository repository;
        public int pageSize = 12;
        public NoteBookController(INoteBookRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1) //http://localhost:53985/NoteBook?page=2
        {
            //отдаем представлению нашу промежуточную модель, в ней есть 1. страница с ноутами на нужной странице и 2. список всех страниц в виде ссылок.
            NoteBooksListViewModel model = new NoteBooksListViewModel
            {
                //делим все товары по страницам и отбираем те для которых указана страница.
                NoteBooks = repository.NoteBooks
                    .Where(n => category == null || n.Category == category) //категория. Здесь два условия выбора!! Если null Тогда все выбрать, иначе = category
                    .OrderBy(notebook => notebook.NoteBookId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ? repository.NoteBooks.Count() : repository.NoteBooks.Where(notebook => notebook.Category == category).Count() 
                },
                CurrentCategory = category
            };
            return View(model);
        }
    }
}

NoteBookStore.WebUI/Views/Nav/Menu.cshtml
@model NoteBookStore.WebUI.Models.NoteBooksCategoryViewModel

<div class="btn-group" style="width:100%;">
    <a href="#" class="btn btn-info disabled" role="button" aria-disabled="true" style="width:98%;left:1.5%;"><h4>Параметры выбора:</h4></a>
</div>

<div class="dropdown btn-group" style="width:100%;margin-top:6%;">
    <a href="#" data-toggle="dropdown" class="btn btn-outline-success" style="width:100%;">
        Производитель
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu" style="width:50%;margin-left:110%;margin-top:-39px;">
        <li>@Html.ActionLink("Все ноуты", "List", "NoteBook", null, new { @class = "dropdown-item", style = "" })</li>

        <li><div class="dropdown-divider"></div></li>

        @foreach (var link in @Model.Categories)
        {
            <li>
                @Html.ActionLink(link, "List", "NoteBook", new { category = link, page = 1 }, new { @class = "dropdown-item", style = "" })
            </li>
        }

    </ul>
</div>

<div class="dropdown btn-group" style="width:100%;">
    <a href="#" data-toggle="dropdown" class="btn btn-outline-success" style="width:100%;">
        Диагональ экрана
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu" style="width:50%;margin-left:110%;margin-top:-39px;">
        <li>@Html.ActionLink("Все ноуты", "List", "NoteBook", null, new { @class = "dropdown-item", style = "" })</li>

        <li><div class="dropdown-divider"></div></li>

        @foreach (var link in @Model.Categories)
        {
            <li>
                @Html.ActionLink(link, "List", "NoteBook", new { category = link, page = 1 }, new { @class = "dropdown-item", style = "" })
            </li>
        }

    </ul>
</div>

<div class="dropdown btn-group" style="width:100%;">
    <a href="#" data-toggle="dropdown" class="btn btn-outline-success" style="width:100%;">
        Процессор
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu" style="width:50%;margin-left:110%;margin-top:-39px;">
        <li>@Html.ActionLink("Все ноуты", "List", "NoteBook", null, new { @class = "dropdown-item", style = "" })</li>

        <li><div class="dropdown-divider"></div></li>

        @foreach (var link in @Model.Categories)
        {
            <li>
                @Html.ActionLink(link, "List", "NoteBook", new { category = link, page = 1 }, new { @class = "dropdown-item", style = "" })
            </li>
        }

    </ul>
</div>
@*

    <div class="btn-group" style="width:100%;margin-top:6%;">
        <button class="btn btn-outline-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width:100%;">
            Производитель
        </button>

        <div class="dropdown-menu" style="width:50%;margin-left:110%;margin-top:-39px;">

            <span id="myDropdown-All">
                @Html.ActionLink("Все ноуты", "List", "NoteBook", null, new { @class = "dropdown-item", style = "" })
            </span>

            <div class="dropdown-divider"></div>

            @foreach (var link in @Model.Categories)
            {
                @Html.RouteLink(
                    link,
                    new
                    {
                        controller = "NoteBook",
                        action = "List",
                        category = link,
                        page = 1
                    },
                    new
                    {
                        @class = "dropdown-item",
                        style = ""
                    })
            }
        </div>
    </div>

    <div class="btn-group" style="width:100%;">
        <button class="btn btn-outline-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width:100%;">
            <span id="myDropdown-name">Диагональ экрана</span>
        </button>
        <div class="dropdown-menu" style="width:50%;margin-left:110%;margin-top:-39px;" ">
            <span id="myDropdown-All">
                @Html.ActionLink("Все ноуты", "List", "NoteBook", null, new { @class = "dropdown-item", style = "" })
            </span>

            <div class="dropdown-divider"></div>

            @foreach (var link in @Model.Categories)
            {
                @Html.RouteLink(
                    link,
                    new
                    {
                        controller = "NoteBook",
                        action = "List",
                        category = link,
                        page = 1
                    },
                    new
                    {
                        @class = "dropdown-item",
                        style = ""
                    })
            }
        </div>
    </div>

    <div class="btn-group" style="width:100%;">
        <button class="btn btn-outline-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width:100%;">
            <span id="myDropdown-name">Процессор</span>
        </button>
        <div class="dropdown-menu" style="width:50%;margin-left:110%;margin-top:-39px;" ">
            <span id="myDropdown-All">
                @Html.ActionLink("Все ноуты", "List", "NoteBook", null, new { @class = "dropdown-item", style = "" })
            </span>

            <div class="dropdown-divider"></div>

            @foreach (var link in @Model.Categories)
            {
                @Html.RouteLink(
                    link,
                    new
                    {
                        controller = "NoteBook",
                        action = "List",
                        category = link,
                        page = 1
                    },
                    new
                    {
                        @class = "dropdown-item",
                        style = ""
                    })
            }
        </div>
    </div>











        <div class="dropdown" style="background-color:#000000;">
        <a href="#" data-toggle="dropdown">
            Ссылка с выпадающим меню
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="#">Пункт 1</a></li>
            <li><a href="#">Пункт 2</a></li>
            <li class="divider"></li>
            <li><a href="#">Пункт 3</a></li>
        </ul>
    </div>









*@



@*
    @Html.ActionLink("Все ноуты", "List", "NoteBook", null, new { @class = "btn btn-block btn-sm" + (@Model.SelectedCategory == null ? " btn-success" : " btn-outline-success"), style = "height:38px; text-align:left; padding-top:16px; padding-left:4px;" })

    @foreach (var link in @Model.Categories)
    {
        @Html.RouteLink(
            link,
            new
            {
                controller = "NoteBook",
                action = "List",
                category = link,
                page = 1
            },
            new
            {
                @class = "btn btn-block btn-sm" + (link == Model.SelectedCategory ? " btn-info" : " btn-outline-info"),
                style= "height:38px; text-align:left; padding-top:16px; padding-left:4px;"
            })
    }
*@