NoteBookStore.WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using NoteBookStore.Domain.Abstract;
using NoteBookStore.Domain.Entities;
using NoteBookStore.WebUI.Models;
using System.Web.Routing;

namespace NoteBookStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private INoteBookRepository repository;
        public CartController(INoteBookRepository repo)
        {
            repository = repo;
        }

        // // // Cart cart - этот объект передевать методам не нужно, его подгонит ModelBinder автоматом.
        public ViewResult Index(Cart cart, string returnUrl) //для отображения содержимого Cart. 
        { 
            return View(
                new CartIndexViewModel
                {
                    Cart = cart,
                    ReturnUrl = returnUrl
                });
        }

        public ActionResult AddToCart(Cart cart, int noteBookId, string returnUrl)
        {
            NoteBook notebook = repository.NoteBooks
                .FirstOrDefault(n => n.NoteBookId == noteBookId);

            if (notebook != null)
            {
                cart.AddItem(notebook, 1);
            }
            return Redirect(returnUrl);
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int noteBookId, string returnUrl)
        {
            NoteBook notebook = repository.NoteBooks
               .FirstOrDefault(n => n.NoteBookId == noteBookId);

            if (notebook != null)
            {
                cart.RemoveLine(notebook);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public ActionResult RemoveAllFromCart(Cart cart, string returnUrl)
        {
            cart.Clear();
            return Redirect( returnUrl );
        }

        public PartialViewResult Summary(Cart cart) //Метод должен визуализировать представление, передавая в качестве данных представления текущий объект Cart (который будет получен с использованием специального связывателя модели).
        {
            return PartialView(cart);
        }
    }
}

NoteBookStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NoteBookStore.Domain.Abstract;
using NoteBookStore.WebUI.Models;

namespace NoteBookStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private INoteBookRepository repository;
        public NavController(INoteBookRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string category = null)
        {
            NoteBooksCategoryViewModel model = new NoteBooksCategoryViewModel
            {
                //вывод всех категорий.
                Categories = repository.NoteBooks
                .Select(notebook => notebook.Category)
                .Distinct()
                .OrderBy(x => x),
                SelectedCategory = category
            };
            return PartialView(model);
        }
    }
}

NoteBookStore.WebUI/Views/Shared/NoteBookSummary.cshtml
@model NoteBookStore.Domain.Entities.NoteBook

<div class="card" style="position:relative; max-height:600px; height:300px; width: 300px; background-color:rgba(23, 129, 129, 0.88); display:inline-block;">
    <img src="~/Content/Images/notebook1.png" width="150" height="150" alt="Card image">
    <div class="card-block">
        <p class="card-text" style="height:100px;overflow:hidden;">@Model.Description</p>
    </div>

    <div style="display:block; position:absolute; top:0; right:0;text-align:right;">
        <h3 style="font:3rem Helvetica; color:#00ff90;">@Model.Name</h3>
        <h7 style="color:chartreuse">@Model.Price.ToString("# руб")</h7>
    </div>

    @using (Html.BeginForm("AddToCart", "Cart", FormMethod.Get, new { @class = "card-text" }))
    {
        @Html.HiddenFor(x => x.NoteBookId)
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
        <div style="display:block; position:absolute; bottom:0; right:0;">
            <input type="submit" class="btn btn-success btn-sm" value="Купить" />
        </div>
    }
</div>

@*
<h3 class="card-title" style="font:3rem Helvetica; color:#00ff90;text-align:right;">@Model.Name</h3>
    <div class="card-subtitle text-muted">
        @using (Html.BeginForm("AddToCart", "Cart", FormMethod.Get, new { @class = "card-text" }))
        {
            @Html.HiddenFor(x => x.NoteBookId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <div style="display:block; position:absolute; top:0; left:0;">
                <input type="submit" class="btn btn-success btn-sm" value="Купить" />
            </div>
            <div style="display:block;position:absolute; top:0;right:0;">
                <h7>@Model.Price.ToString("# руб")</h7>
            </div>
        }
    </div>
*@

NoteBookStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>НоутStore</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="\Content\Images\favicon_notebook.ico" />

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery.unobtrusive-ajax")
    @Scripts.Render("~/bundles/jquery_ui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/MyJS")
    @Scripts.Render("~/bundles/mCustomScrollbar")

    @Styles.Render("~/Content/css_bootstrap")
    @Styles.Render("~/Content/css_MyCssMarkUp")
    @Styles.Render("~/Content/css_mCustomScrollbar")

</head>
<body>
    <div class="container-fluid" style="margin:2rem;">
        <div class="row flex-items-xs-center">
            <div class="col-xs-12" style="text-align:center;">
                <div style="display:inline-block; position:relative;">
                    <img src="~/Content/Images/NoteBookStore_main3.png" width="700" style="opacity:0.95;"> @*<a href="@Url.Action("Index", "Home")"><img src="~/Content/Images/NoteBookStore_main3.png" width="500" height="500" style="opacity:0.95;"></a>*@
                    <div style="text-align:center; width:100%; left:10%; top:24%; position:absolute;">
                        <div style="display:inline-block;width:50%;">
                            @Html.Action("Menu", "Nav")
                        </div>
                    </div>
                    <div style="top:18%; left:15%; position:absolute;">
                        <div id="dock-container" style="display:inline-block;">@*width:60%;*@
                            <div id="dock">
                                <ul>
                                    <li>
                                        <span>Вход</span>
                                        @*<a href="#"><img src="Content/Images/DocPanel/img/1.png" /></a>*@
                                        @{
                                            if (HttpContext.Current.User.Identity.IsAuthenticated)
                                            {
                                                <a href="@Url.Action("LogOut", "Account", new { pathView = Request.Url.PathAndQuery })" style="width: 60px; height: 60px;">
                                                    @*<img src="~/Content/Images/spaceLogIn_empty.png" style="opacity:0.8;width: 60px; height: 60px;" alt="Пример">*@
                                                    <div class="AvatarHasExit_LogOut_none" style="position:relative;">
                                                        <img src="~/Content/Images/spaceLogIn_empty.png" style="opacity:0.8;width: 60px; height: 60px;" alt="Пример">

                                                        <div id="myDiv"style="top:20.1%; left:1%; position:absolute;">
                                                            <img alt="Avatar" style="opacity:0.95; border-radius:50px; width:56%; height:56%;" src="@Html.returnAvatarPath(HttpContext.Current.User)" />
                                                        </div>

                                                        <div class="" style="top:10%; left:0%; position:absolute;">
                                                            <div>
                                                                <img alt="Avatar" style="border-radius:50px;opacity:0.6; width:60%; height:60%;" src="~/Content/Images/X.png" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </a>
                                            }
                                            else
                                            {
                                                <a href="@Url.Action("LoginRegister", "Account",  new { pathView = Request.Url.PathAndQuery })">
                                                    <img src="~/Content/Images/spaceLogIn.png" width="60" height="60" style="opacity:0.8;" alt="Пример"> @*@Html.ActionLink("LOG IN SIGN UP", new { pathView = Request.Url.PathAndQuery }, new { })*@
                                                </a>
                                            }
                                        }
                                    </li>
                                    <li>
                                        <span>Корзина</span>
                                        @*<a href="#"><img src="~/Content/Images/spaceCart_empty.png" /></a>*@
                                        @Html.Action("Summary", "Cart")

                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           @* <div class="col-xs-12;">
                @Html.Action("Summary", "Cart")
            </div>*@
        </div>
    </div>

    @RenderBody()

    <script>
         @*scroll*@
        (function ($) {
            $(window).on("load", function () {
                $("body").mCustomScrollbar({
                    setWidth: "100%",
                    setHeight: "100%",
                });
            });
        })(jQuery);
        $('.body').css('height', ($('.contentContainer').height()).mCustomScrollbar('update'));/* https://github.com/malihu/malihu-custom-scrollbar-plugin/issues/68 */
    </script>

    @*выпод подпункта dropdows lista, заменяет текущее имя*@
    <script type="text/javascript">
        $(".dropdown-menu li a").click(function(){
          $(this).parents(".dropdown").find('a:first').html($(this).text() + ' <span class="caret"></span>');
        });
    </script>

    @RenderSection("scripts", required: false)

</body>
</html>